version: '3'
services:
  frsocket:
    container_name: frsocket
    build: .
    command: go run main.go
    volumes:
      - ./:/go/src/app
    working_dir: /go/src/app
    ports:
      - "8080:8080"
    environment:
      PORT: 8080